# Install script for directory: /Users/yushihang/Documents/HSBC/polygonID/witnesscalc

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump")
endif()

set(CMAKE_BINARY_DIR "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64")

if(NOT PLATFORM_NAME)
  if(NOT "$ENV{PLATFORM_NAME}" STREQUAL "")
    set(PLATFORM_NAME "$ENV{PLATFORM_NAME}")
  endif()
  if(NOT PLATFORM_NAME)
    set(PLATFORM_NAME iphoneos)
  endif()
endif()

if(NOT EFFECTIVE_PLATFORM_NAME)
  if(NOT "$ENV{EFFECTIVE_PLATFORM_NAME}" STREQUAL "")
    set(EFFECTIVE_PLATFORM_NAME "$ENV{EFFECTIVE_PLATFORM_NAME}")
  endif()
  if(NOT EFFECTIVE_PLATFORM_NAME)
    set(EFFECTIVE_PLATFORM_NAME -iphoneos)
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/tests.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/tests.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/tests.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/tests.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/tests.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/tests.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/tests.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/tests.app" USE_SOURCE_PERMISSIONS)
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/test_platform.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/test_platform.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/test_platform.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/test_platform.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/test_platform.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/test_platform.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/test_platform.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/test_platform.app" USE_SOURCE_PERMISSIONS)
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/authV2.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/authV2.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/authV2.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/authV2.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/authV2.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/authV2.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/authV2.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/authV2.app" USE_SOURCE_PERMISSIONS)
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_authV2.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_authV2.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_authV2.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_authV2.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_authV2.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_authV2.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_authV2.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_authV2.dylib")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_authV2.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_authV2.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_authV2.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_authV2.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_authV2.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_authV2.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_authV2.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_authV2.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_authV2.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_authV2.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_authV2.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_authV2.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_authV2.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_authV2.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_authV2.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_authV2.a")
    endif()
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQueryMTPV2.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQueryMTPV2.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQueryMTPV2.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQueryMTPV2.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQueryMTPV2.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQueryMTPV2.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQueryMTPV2.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQueryMTPV2.app" USE_SOURCE_PERMISSIONS)
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQueryMTPV2.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQueryMTPV2.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQueryMTPV2.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQueryMTPV2.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2.dylib")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2.a")
    endif()
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQuerySigV2.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQuerySigV2.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQuerySigV2.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQuerySigV2.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQuerySigV2.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQuerySigV2.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQuerySigV2.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQuerySigV2.app" USE_SOURCE_PERMISSIONS)
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQuerySigV2.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQuerySigV2.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQuerySigV2.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQuerySigV2.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2.dylib")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2.a")
    endif()
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQueryMTPV2OnChain.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQueryMTPV2OnChain.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQueryMTPV2OnChain.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQueryMTPV2OnChain.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQueryMTPV2OnChain.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQueryMTPV2OnChain.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQueryMTPV2OnChain.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQueryMTPV2OnChain.app" USE_SOURCE_PERMISSIONS)
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.dylib")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQueryMTPV2OnChain.a")
    endif()
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQuerySigV2OnChain.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQuerySigV2OnChain.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQuerySigV2OnChain.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQuerySigV2OnChain.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQuerySigV2OnChain.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQuerySigV2OnChain.app" USE_SOURCE_PERMISSIONS)
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app/credentialAtomicQuerySigV2OnChain.app")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/app" TYPE DIRECTORY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/credentialAtomicQuerySigV2OnChain.app" USE_SOURCE_PERMISSIONS)
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2OnChain.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2OnChain.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2OnChain.dylib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.dylib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE SHARED_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2OnChain.dylib")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libwitnesscalc_credentialAtomicQuerySigV2OnChain.a")
    endif()
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Debug${EFFECTIVE_PLATFORM_NAME}/libfr.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libfr.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libfr.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libfr.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/Release${EFFECTIVE_PLATFORM_NAME}/libfr.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libfr.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libfr.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libfr.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libfr.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libfr.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libfr.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libfr.a")
    endif()
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libfr.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libfr.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libfr.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libfr.a")
    endif()
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib/libgmp.a")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/lib" TYPE FILE FILES "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/depends/gmp/package_ios_simulator_x86_64/lib/libgmp.a")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/bin/auth.dat;/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/bin/authV2.dat;/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/bin/credentialAtomicQuerySigV2.dat;/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/bin/credentialAtomicQueryMTPV2.dat;/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/bin/credentialAtomicQuerySigV2OnChain.dat;/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/bin/credentialAtomicQueryMTPV2OnChain.dat")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/bin" TYPE FILE FILES
    "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/src/auth.dat"
    "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/src/authV2.dat"
    "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/src/credentialAtomicQuerySigV2.dat"
    "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/src/credentialAtomicQueryMTPV2.dat"
    "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/src/credentialAtomicQuerySigV2OnChain.dat"
    "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/src/credentialAtomicQueryMTPV2OnChain.dat"
    )
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/include/witnesscalc.h;/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/include/witnesscalc_authV2.h;/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/include/witnesscalc_credentialAtomicQuerySigV2.h;/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/include/witnesscalc_credentialAtomicQueryMTPV2.h;/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/include/witnesscalc_credentialAtomicQuerySigV2OnChain.h;/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/include/witnesscalc_credentialAtomicQueryMTPV2OnChain.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  file(INSTALL DESTINATION "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/package_ios_simulator_x86_64/include" TYPE FILE FILES
    "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/src/witnesscalc.h"
    "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/src/witnesscalc_authV2.h"
    "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/src/witnesscalc_credentialAtomicQuerySigV2.h"
    "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/src/witnesscalc_credentialAtomicQueryMTPV2.h"
    "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/src/witnesscalc_credentialAtomicQuerySigV2OnChain.h"
    "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/src/witnesscalc_credentialAtomicQueryMTPV2OnChain.h"
    )
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/src/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/Users/yushihang/Documents/HSBC/polygonID/witnesscalc/build_witnesscalc_ios_simulator_x86_64/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
